set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

# Native printer firmware: soft-float EABI and /lib/ld-linux.so.3.
set(TOOLCHAIN_TRIPLET arm-unknown-linux-gnueabi)
set(TOOLCHAIN_ROOT "/Volumes/x-tools/${TOOLCHAIN_TRIPLET}")
set(TOOLCHAIN_BIN "${TOOLCHAIN_ROOT}/bin")

set(CMAKE_C_COMPILER "${TOOLCHAIN_BIN}/${TOOLCHAIN_TRIPLET}-gcc")
set(CMAKE_CXX_COMPILER "${TOOLCHAIN_BIN}/${TOOLCHAIN_TRIPLET}-g++")
set(CMAKE_AR "${TOOLCHAIN_BIN}/${TOOLCHAIN_TRIPLET}-ar")
set(CMAKE_AS "${TOOLCHAIN_BIN}/${TOOLCHAIN_TRIPLET}-as")
set(CMAKE_LD "${TOOLCHAIN_BIN}/${TOOLCHAIN_TRIPLET}-ld")
set(CMAKE_STRIP "${TOOLCHAIN_BIN}/${TOOLCHAIN_TRIPLET}-strip")
set(CMAKE_RANLIB "${TOOLCHAIN_BIN}/${TOOLCHAIN_TRIPLET}-ranlib")

set(CMAKE_FIND_ROOT_PATH "${TOOLCHAIN_ROOT}/${TOOLCHAIN_TRIPLET}/sysroot")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
